# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f673fcdcf8f15438e415e1c9a37de17cbb7e234a1782c8fc43406c4b66a0ece9ea38b9da87e71ad02d2f5b411bbed40d4c9cf5002e09df19d0cabfadc8391abe

test:
  secret_key_base: 296af564352628cbf951b63a49572f5d752f84f1fe74d01040efdfb5d38c00e275faf0bfd4a27c81ac6da079e68038ad02a58f253750c9229095b5fb492ee4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
